<h1>Seznam knih</h1>
<div><a href="bookEditor/" class="btn bg-primary text-white">Pridat knihu</a></div>
<table>
    <thead>
    <tr>
        <th>Nazev knihy</th>
        <th>Autor</th>
        <th>Kategorie</th>
        <th>Serie</th>
    </tr>
    </thead>
    <tbody>
    <?php

    /** @var \dto\BookDto $book */
    foreach ($this->multipleBooks as $book) : ?>
        <tr>
            <td><a href="books/<?= $book->getId() ?>"><?= $book->getTitle()?></a></td>
            <td><?= $book->getAuthor()?></td>
            <td><?= $book->getCategory()?></td>
            <td><?= $book->getSeries()?></td>
            <td><span><a href="bookEditor/<?= $book->getId()?>" class="btn bg-warning text-white">Editovat</a></span>
                <span><a href="books/<?= $book->getId() ?>/delete" class="btn bg-danger text-white">Odstranit</a></span></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>