<h1>Seznam knih</h1>
<div><a href="booksEditor/" class="btn bg-primary text-white">Pridat knihu</a></div>
<table>
    <thead>
    <tr>
        <th>Nazev knihy</th>
        <th>Autor</th>
        <th>Kategorie</th>
        <th>Serie</th>
    </tr>
    </thead>
    <tbody>
    <?php

    /** @var \dto\BookDto $book */
    foreach ($this->data as $book) : //todo nastavit vsechny vypisujici se promenne pres getter ?>
        <tr>
            <td><a href="books/<?= $book['id'] ?>"><?= $book->getTitle()?></a></td>
            <td><?= $book['author']?></td>
            <td><?= $book['category']?></td>
            <td><?= $book['series']?></td>
            <td><span><a href="booksEditor/<?= $book['id'] ?>" class="btn bg-warning text-white">Editovat</a></span>
                <span><a href="books/<?= $book['id'] ?>/delete" class="btn bg-danger text-white">Odstranit</a></span></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>